# German reading summaries for the 45 selected papers.
# key = paper id in papers.json. Fields:
#   chapter, fig (figure file stem), core, study, results[], do[], dont[], limits, orig, basis
# basis: "Volltext" | "Abstract" (+ note)

CHAPTERS = [
    ("1", "Grundlagen der Wahrnehmung", "Welche visuellen Kanäle wir wie genau ablesen – und warum die klassische Rangfolge nur die halbe Wahrheit ist."),
    ("2", "Aufmerksamkeit & Gedächtnis", "Wohin Menschen schauen, was sie behalten und wann Deko hilft oder schadet."),
    ("3", "Text, Titel & Takeaways", "Wie Titel, Captions, Annotationen und Anordnung steuern, was Leser mitnehmen."),
    ("4", "Irreführung & Vertrauen", "Wie Charts täuschen – absichtlich oder nicht – und was das mit Vertrauen macht."),
    ("5", "Entscheidungen, Unsicherheit & Bias", "Wie Visualisierungen Urteile, Kausalschlüsse und Wahrscheinlichkeitsdenken beeinflussen."),
    ("6", "Visualization Literacy", "Was das Publikum überhaupt lesen kann – und wie man es misst."),
    ("7", "Storytelling & Engagement", "Narrative Formen, Animation, Comics und Emotion: was Engagement wirklich bringt."),
    ("8", "Business & Überblick", "Tabellen im Arbeitsalltag und die beste Gesamt-Zusammenfassung des Feldes."),
]

P = {
# ============================================================== 1 Wahrnehmung
98: dict(chapter="1", fig="98-cleveland-ranking",
 core="Das Fundament der Disziplin: Menschen lesen Werte aus Position am genauesten ab, aus Winkel, Fläche und Farbe deutlich ungenauer.",
 study="Theorie der „elementaren Wahrnehmungsaufgaben“ plus Laborexperimente, in denen Probanden Verhältnisse zwischen zwei markierten Werten schätzten (z. B. Position vs. Winkel, ausgerichtete vs. gestapelte Balken).",
 results=["Rangfolge: Position auf gemeinsamer Skala > Position auf versetzten Skalen > Länge/Richtung/Winkel > Fläche > Volumen/Krümmung > Schattierung/Sättigung",
          "Positionsurteile waren im Experiment deutlich genauer als Winkelurteile (Torte vs. Balken)",
          "Gestapelte und geteilte Balken schneiden schlechter ab als ausgerichtete Balken",
          "Empfehlung der Autoren: Punktdiagramme (dot charts) statt Torten und gestapelter Balken"],
 do=["Wichtigste Vergleiche auf eine gemeinsame Grundlinie legen (Balken, Punkte)", "Punktdiagramme als Alternative zu Torten erwägen"],
 dont=["Präzise Vergleiche über Fläche, Volumen oder Farbintensität verlangen"],
 limits="Getestet wurde nur das Schätzen von Verhältnissen zwischen zwei Werten – spätere Arbeiten (McColeman 2021, Lee 2026) zeigen, dass die Rangfolge bei anderen Aufgaben kippt.",
 orig="Die Rangfolge-Tabelle und die Fehlerplots zu Position vs. Winkel im Paper (S. 531–554).",
 basis="Abstract + Standardwissen (PDF ist ein Scan ohne Textebene)"),

99: dict(chapter="1", fig="99-heer-bostock",
 core="Crowdsourcing über Mechanical Turk liefert dieselben Wahrnehmungsergebnisse wie Laborstudien – der methodische Startschuss für die meisten Studien in diesem Dossier.",
 study="Replikation von Cleveland & McGill und Stone & Bartram auf Mechanical Turk; neue Experimente zu Rechteckflächen (Treemaps), Charthöhe und Gitterlinien.",
 results=["Die Rangfolge Position > Länge > Winkel > Fläche wurde repliziert",
          "Rechteckflächen werden etwa so genau verglichen wie Kreisflächen; Quadrate (Seitenverhältnis 1) waren am schwierigsten",
          "Gitterlinien: Alpha ≈ 0,2 als sicherer Standard bestätigt",
          "Mit Qualifikationsaufgabe nur 0,75 % Ausreißer; ohne waren >10 % der Antworten unbrauchbar",
          "Knapp die Hälfte aller Trials (45,7 %) wurde von 52 „Streakern“ erledigt"],
 do=["Gitterlinien dezent halten (hell, niedrige Deckkraft)", "Für eigene Tests mit Nutzern: klare Aufgaben mit überprüfbaren Antworten"],
 dont=["Treemaps für präzise Größenvergleiche nahezu quadratischer Kacheln einsetzen"],
 limits="Zeitmessungen sind im Crowdsourcing unzuverlässig (Median 42 s pro Trial statt wenige Sekunden).",
 orig="Fig. 4 (Replikation der Proportionsurteile), Fig. 5 (Rechtecke nach Seitenverhältnis), Fig. 8 (Gitterlinien-Alpha).",
 basis="Volltext"),

109: dict(chapter="1", fig="109-talbot-bars",
 core="Gestapelte Balken sind schwer zu lesen, weil die Segmente nicht ausgerichtet sind und Nachbarn stören – eine kleine Lücke hilft überraschend.",
 study="Vier Crowdsourcing-Experimente (je ca. 50 Personen), die Cleveland & McGills Balkenaufgaben in ihre Einzelfaktoren zerlegen: Abstand, Ablenker, Ausrichtung, Markierung.",
 results=["Vergleiche von Segmenten im selben Stapel: durchschnittlich 7,38 Prozentpunkte absoluter Fehler",
          "Nicht ausgerichtete statt ausgerichtete Balken: +1,15 Prozentpunkte Fehler",
          "Ablenkende Nachbarsegmente: +0,37 Prozentpunkte",
          "Eine Lücke zwischen den verglichenen Segmenten senkt den Fehler um 0,87 Prozentpunkte",
          "Weit auseinanderliegende Balken sind schwerer zu vergleichen, besonders bei kleinen Referenzbalken"],
 do=["Die wichtigste Reihe an die Grundlinie legen", "Zu vergleichende Balken nebeneinander platzieren; Sortieren und Referenzlinien nutzen"],
 dont=["Präzise Vergleiche mittlerer Segmente in gestapelten Balken erwarten"],
 limits="Abstrakte Aufgaben ohne Kontext; Effekte in Prozentpunkten sind klein, aber systematisch.",
 orig="Fig. 3–5 (Abstandseffekt), Fig. 8–9 (Unalignment), Fig. 12–13 (Bias in gestapelten Balken).",
 basis="Volltext"),

108: dict(chapter="1", fig="108-harrison-weber",
 core="Korrelation liest man am präzisesten aus Scatterplots; wie gut andere Charts funktionieren, hängt sogar davon ab, ob die Korrelation positiv oder negativ ist.",
 study="Großes Crowdsourcing-Experiment (n = 1.687) mit 9 Charttypen; per Staircase-Verfahren wurde die kleinste noch erkennbare Korrelationsdifferenz (JND) bestimmt.",
 results=["Für alle Charttypen folgt die Präzision dem Weber-Gesetz (je höher r, desto feiner die Unterscheidung)",
          "Scatterplots sind für positive und negative Korrelation gleich gut",
          "Parallele Koordinaten funktionieren bei negativer Korrelation so gut wie Scatterplots, bei positiver deutlich schlechter",
          "Sechs Kombinationen (u. a. gestapelte Fläche/Balken/Linie positiv, Donut positiv) lagen so oft auf Zufallsniveau, dass sie ausgeschlossen wurden"],
 do=["Für Zusammenhänge zwischen zwei Größen einen Scatterplot wählen"],
 dont=["Korrelationen in gestapelten Flächen oder Donuts zeigen"],
 limits="Getestet wurden r-Werte von 0,3 bis 0,8; die Re-Analyse von Kay & Heer (2016) zeigt, dass das Weber-Modell die Daten nicht optimal beschreibt.",
 orig="Fig. 3 (die 9 Charttypen), Fig. 6 (Weber-Geraden), Fig. 7 (Rangfolge).",
 basis="Volltext"),

9: dict(chapter="1", fig="9-kay-heer",
 core="Eine saubere statistische Neuauswertung bestätigt: Scatterplots sind für Korrelation die robusteste Wahl – mit geringer Streuung zwischen Personen.",
 study="Bayes'sche Neuauswertung der Harrison-Daten (1.687 Personen) mit Log-Transformation und zensierter Regression, inklusive der vorher verworfenen Charttypen.",
 results=["Vier Präzisionsgruppen statt einer Gesamtrangfolge",
          "Jede Gruppe ist im Schnitt mindestens ≈1,5–2× präziser als die nächstschlechtere",
          "Scatterplots (positiv und negativ) und parallele Koordinaten (negativ) bilden die Spitzengruppe",
          "Scatterplots haben zudem eine geringe Streuung zwischen Individuen – sie funktionieren für fast alle"],
 do=["Scatterplot als Standard für Korrelation", "Rangfolgen aus Studien als Gruppen („ähnlich gut“) lesen, nicht als exakte Plätze"],
 dont=["Kleine Rangunterschiede zwischen Charttypen überinterpretieren"],
 limits="Methodenpapier – keine neuen Daten, aber wichtige Lektion zur Aussagekraft von „Rankings“.",
 orig="Fig. 8 (finales Modell, Partial Ranking und Präzisionsverhältnisse), Fig. 9 (Streuung zwischen Personen).",
 basis="Volltext"),

17: dict(chapter="1", fig="17-mccoleman",
 core="Die berühmte Kanal-Rangfolge gilt nicht allgemein: Sollen Leute sich Werte merken, zählt die Anzahl der Datenpunkte viel mehr als der gewählte Kanal.",
 study="49 Personen sahen kurz Charts mit 2, 4 oder 8 Werten in sechs Kanälen (Balken-Position, Linie, Länge, Winkel, Fläche, Helligkeit) und mussten sie danach aus dem Gedächtnis nachzeichnen. Bayes'sches Mehrebenenmodell für Verzerrung, Präzision und Fehler.",
 results=["Die Cleveland-McGill-Rangfolge hielt nicht – nicht einmal bei nur 2 Werten",
          "Die Anzahl der Marks hatte eine Größenordnung mehr Einfluss als die Kanalwahl",
          "Mit 92 % Wahrscheinlichkeit ist die Erinnerung bei 2 Marks weniger verzerrt als bei 8",
          "Kleine Werte werden über-, große unterschätzt; am wenigsten Verzerrung um die Mitte der Skala",
          "Länge und Balken-Position verzerren am wenigsten; Fläche ist überraschend präzise, aber stärker verzerrt"],
 do=["Pro Chart wenige Werte zeigen, wenn sie erinnert werden sollen", "Die Kernzahl zusätzlich als Text nennen"],
 dont=["Aus der klassischen Rangfolge ableiten, dass ein Kanal immer besser ist"],
 limits="Eine spezifische Aufgabe (Nachzeichnen); Liniencharts wurden systematisch zu niedrig gezeichnet.",
 orig="Fig. 1 (klassische vs. neue Rangfolge), Fig. 7 (Effekte der Markanzahl), Fig. 8 (probabilistische Rangfolgen).",
 basis="Volltext"),

28: dict(chapter="1", fig="28-lee-popout",
 core="Kanal-Effektivität ist mehrdimensional: Was sich genau ablesen lässt (Länge), springt nicht unbedingt ins Auge (dafür sind Fläche und Farbton top).",
 study="Crowdsourcing-Experimente zu 7 Kanälen (Position, Länge, Neigung, Fläche, Krümmung, Helligkeit, Sättigung) ohne Chart-Gerüst, in 4 Aufgaben: Genauigkeit, Unterscheidbarkeit, Trennbarkeit, Pop-out (100 ms Anzeige).",
 results=["Pop-out-Trefferquote: Fläche 91,7 %, Farbton 90,4 %, Position 88,9 % … Länge nur 80,3 %, Helligkeit 77,0 %",
          "Genauigkeit hängt stark davon ab, ob es einen festen räumlichen Anker gibt (z. B. gemeinsame Grundlinie)",
          "Stärkste Interferenz: Variiert die Fläche, bricht das Ablesen von Neigung fast auf Zufallsniveau ein",
          "Variierende Helligkeit stört Sättigungsurteile, aber nicht umgekehrt",
          "Länge bleibt robust, egal welcher zweite Kanal variiert"],
 do=["Zum Hervorheben (Ausreißer, Alarm) Farbton oder Größe nutzen", "Für präzises Ablesen Länge/Position mit gemeinsamer Grundlinie"],
 dont=["Neigung und Fläche gleichzeitig für zwei Variablen nutzen", "Helligkeit oder Sättigung als einziges Hervorhebungsmittel"],
 limits="Preprint (August 2026, noch nicht begutachtet); abstrakte Stimuli ohne Chart-Kontext.",
 orig="Fig. 1 (Studiendesign – die Grafik, die dir gefallen hat), Fig. 2 (Genauigkeit), Fig. 4 (Unterscheidbarkeit), Table 3 (Interferenz-Matrix), Fig. 5 (Pop-out).",
 basis="Volltext"),

7: dict(chapter="1", fig="7-skau-kosara-donut",
 core="Torten und Donuts werden nicht über den Winkel gelesen, sondern über Bogenlänge und Fläche – deshalb ist ein Donut so genau wie eine Torte.",
 study="Zwei Crowdsourcing-Studien: (1) Torten-Varianten, die jeweils nur Winkel, nur Bogen oder nur Fläche zeigen; (2) Donuts mit Innenradius von 0 % bis 97 % (93 gültige Teilnehmende).",
 results=["Reine Winkel-Varianten schnitten deutlich am schlechtesten ab – Winkel ist der unwichtigste Hinweisreiz",
          "Donuts mit 20–80 % Innenradius waren so genau wie die Torte (Log-Fehler 1,16–1,33 vs. 1,33)",
          "Erst der sehr dünne Ring (97 %) war schlechter (1,55)",
          "Beide sind trotzdem ungenauer als Balkendiagramme"],
 do=["Wenn schon Teil-vom-Ganzen als Kreis, dann darf es ein Donut sein – die Mitte eignet sich für die Kernzahl", "Segmente mit gleichem Radius zeichnen"],
 dont=["Radius als Dekoration variieren", "Explodierte Tortenstücke, wenn Segmente summiert werden sollen"],
 limits="Nur Diagramme mit zwei Segmenten; Männer und Jüngere waren im Schnitt genauer.",
 orig="Fig. 1 & 4 (Encoding-Varianten), Table 1 (Fehler je Variante), Fig. 10–11 & Table 2 (Innenradius).",
 basis="Volltext"),

0: dict(chapter="1", fig="0-kim-heer-illustration",
 core="Welche Kodierung am besten ist, hängt von Aufgabe und Datenverteilung ab – farbige Scatterplots sind gut für Einzelwerte, aber schlecht für Gruppenvergleiche bei vielen Kategorien.",
 study="Crowdsourcing-Experiment: 12 Kodierungen dreidimensionaler Daten (1 Kategorie, 2 Kennzahlen) über x, y, Farbe, Größe und Facettierung; 4 Aufgaben (Wert ablesen, Werte vergleichen, Maximum finden, Durchschnitte vergleichen) × 24 Datenverteilungen.",
 results=["Position (x/y) bleibt insgesamt am stärksten, aber die Rangfolge verschiebt sich je nach Aufgabe",
          "Farbige Scatterplots: gut zum Vergleichen einzelner Punkte, schlecht für Durchschnittsvergleiche, sobald die Zahl der Kategorien steigt",
          "Mehr Überlappung/Gedränge verschlechtert die Leistung",
          "Aufgabe und Datenmerkmale sollten in automatische Chart-Empfehlungen einfließen"],
 do=["Bei vielen Kategorien facettieren (Small Multiples) statt alles einzufärben", "Vor der Chartwahl klären: Einzelwerte oder Gruppenaussage?"],
 dont=["20 Farben in einem Scatterplot, wenn die Botschaft ein Gruppenvergleich ist"],
 limits="Nur Punkt-basierte Charts; binäre Fragen mit fester Schwierigkeit.",
 orig="Fig. 1 & 3 (Stimuli), Fig. 5 & 7 (Effektivitäts-Rankings nach Aufgabe und Datenverteilung).",
 basis="Volltext"),

27: dict(chapter="1", fig="27-saket-matrix",
 core="„No one size fits all“: Tabelle, Linie, Balken, Scatter und Torte gewinnen jeweils bei anderen Aufgaben – sogar die Torte hat ihre Stärken.",
 study="Crowdsourcing-Experiment mit fünf kleinen Charttypen (5–34 Datenpunkte) über 10 typische Analyseaufgaben und zwei Datensätze; gemessen wurden Genauigkeit, Zeit und Präferenz.",
 results=["Cluster finden: Balken (und Torte) schnell und genau; Balken bevorzugt",
          "Korrelation: Linie und Scatter am genauesten und schnellsten; Tabelle und Torte meiden",
          "Ausreißer: Scatterplot am besten",
          "Abgeleitete Werte berechnen: Tabelle am schnellsten, Linie am ungenauesten",
          "Torten sind bei Cluster, Extremwert, Filter, Wert ablesen und Spannweite so gut wie die anderen",
          "Präferenzen korrelieren mit Leistung, aber auch mit Vertrautheit („Balken kenne ich“)"],
 do=["Die Aufgabe des Lesers bestimmt den Charttyp", "Tabellen anbieten, wenn exakte Werte gebraucht werden"],
 dont=["Torten oder Tabellen für Korrelationen", "Linien, wenn einzelne Werte exakt abgelesen werden sollen"],
 limits="Statische, kleine Charts; Torten hatten Datenbeschriftungen, was ihnen half.",
 orig="Fig. 3 (paarweise Vergleiche über alle Aufgaben), Guidelines G1–G5 in Abschnitt 6.3.",
 basis="Volltext"),

23: dict(chapter="1", fig="23-quadri-survey",
 core="Die Übersicht zu Wahrnehmungsstudien seit 1980, geordnet nach Aufgabe – ein Nachschlagewerk, dessen Kernbotschaft lautet: Effektivität ist immer aufgabenabhängig.",
 study="Systematisches Literatur-Review zu Wahrnehmungsstudien seit 1980, gegliedert nach Low-Level-Aufgabe, visueller Kodierung und Charttyp.",
 results=["Kein Charttyp ist für alle Aufgaben optimal; selbst Varianten desselben Typs haben unterschiedliche Stärken",
          "Viele als „Fakt“ geltende Guidelines wurden nie ausreichend geprüft (z. B. sind parallele Koordinaten weniger schwer als ihr Ruf)",
          "Kaum Replikationen; viele Studien mit eingeschränkten Stichproben (z. B. Informatikstudierende)",
          "Forschung konzentriert sich auf Scatter-, Balken- und Liniencharts"],
 do=["Guidelines als kontextabhängige Evidenz lesen: Welche Aufgabe, welches Publikum?"],
 dont=["Einzelstudien zu universellen Regeln erklären"],
 limits="Konzentriert sich auf Low-Level-Aufgaben; High-Level-Verständnis ist kaum abgedeckt.",
 orig="Table 2 (Übersicht Charttyp × Aufgabe) und die Abschnitte je Aufgabe als Nachschlagewerk.",
 basis="Volltext"),

# ============================================================== 2 Aufmerksamkeit
100: dict(chapter="2", fig="100-borkin-memorability",
 core="Visualisierungen werden konsistent erinnert oder vergessen – und Farbe, erkennbare Objekte und visuelle Dichte machen sie einprägsamer.",
 study="Größte Studie ihrer Zeit: 2.070 Visualisierungen aus Nachrichten, Regierungsberichten, Wissenschaft und Infografiken; 410 davon im Wiedererkennungstest auf Mechanical Turk.",
 results=["Wiedererkennungsrate 55 % (Szenenfotos: 68 %, Gesichter: 54 %)",
          "Hohe Übereinstimmung zwischen Personengruppen (Rangkorrelation 0,81) – Einprägsamkeit ist eine Eigenschaft der Grafik",
          "Mit Piktogrammen/erkennbaren Objekten: Score 1,93 vs. 1,14 ohne",
          "≥7 Farben: 1,71 vs. 2–6 Farben 1,48 vs. 1 Farbe 1,18",
          "Niedrige „Data-Ink-Ratio“ (viel Deko) war einprägsamer: 1,81 vs. 1,23",
          "Gängige Charts (Balken, Linie) waren weniger einprägsam als ungewöhnliche (Baum, Netzwerk, Matrix)"],
 do=["Für Präsentationen, die in Erinnerung bleiben sollen: ein erkennbares Bild- oder Farbelement einsetzen"],
 dont=["Einprägsamkeit mit Verständnis verwechseln – gemessen wurde nur, ob das Bild wiedererkannt wird"],
 limits="Wiedererkennung nach 1 Sekunde Anzeige, nicht Verständnis; die Folgestudie (Borkin 2016) schließt diese Lücke.",
 orig="Fig. 1 (die einprägsamsten und am wenigsten einprägsamen Beispiele), Fig. 4–7 (Scores nach Attributen).",
 basis="Volltext"),

35: dict(chapter="2", fig="35-borkin-2016",
 core="Titel und Text sind die Blickmagneten jeder Visualisierung – und was „auf einen Blick“ einprägsam ist, wird auch inhaltlich besser verstanden.",
 study="Eye-Tracking mit 33 Personen auf 393 annotierten Visualisierungen, dazu Tausende freie Textbeschreibungen der Grafiken aus dem Gedächtnis.",
 results=["Titel und begleitender Text ziehen die meisten Fixationen an und bestimmen, was erinnert wird",
          "Passend eingesetzte Piktogramme stören das Verständnis nicht und verbessern das Wiedererkennen",
          "Redundanz (Botschaft in Titel UND Grafik) hilft beim Übermitteln der Botschaft",
          "Einprägsame Visualisierungen vermitteln ihre Botschaft auch besser"],
 do=["Die Kernaussage in den Titel schreiben", "Botschaft redundant kodieren: Titel + Hervorhebung im Chart"],
 dont=["Rein beschreibende Titel wie „Umsatz 2025“"],
 limits="Quelle: Abstract und bekannte Ergebnisse; das Paper-PDF war hinter einer IEEE-Schranke.",
 orig="Die Heatmaps der Blickfixationen und die Analyse nach Elementtypen (Titel, Labels, Daten) im Paper.",
 basis="Abstract (Volltext hinter IEEE-Paywall)"),

38: dict(chapter="2", fig="38-bubbleview",
 core="Man braucht keinen Eye-Tracker: Maus-Klicks auf ein verschwommenes Bild bilden die Blicke auf Visualisierungen zu bis zu 92 % nach.",
 study="10 Experimente mit 28 Parameterkombinationen; Nutzer klicken auf ein unscharfes Bild, um kleine Bereiche scharf zu sehen. Vergleich mit Labor-Eye-Tracking auf Visualisierungen, Fotos, Webseiten und Grafikdesigns.",
 results=["Visualisierungen mit Beschreibungsaufgabe: Klicks erklären 90 % der Fixationen (10 Personen), 92 % (20 Personen)",
          "Naturbilder und Webseiten: bis zu 78 %",
          "Klick-Daten sind sauberer als kontinuierliche Mausbewegungen und haben keinen Zentrums-Bias",
          "Blasengröße 30–50 px funktioniert über viele Bildtypen am besten"],
 do=["Günstige Aufmerksamkeitstests eigener Dashboards/Folien mit einer Handvoll Personen durchführen"],
 dont=["Unbewusste Pop-out-Effekte mit Klick-Methoden messen wollen – die erfasst BubbleView nicht"],
 limits="Klicks erfassen bewusste Aufmerksamkeit, nicht reflexhafte Blicke.",
 orig="Fig. 1 (Fixations- vs. Klick-Heatmap), Tables II–IV (Übereinstimmung je Bildtyp).",
 basis="Volltext"),

37: dict(chapter="2", fig="37-bylinskii-importance",
 core="Ein neuronales Netz sagt vorher, welche Teile einer Visualisierung Menschen wichtig finden – vor allem Titel, Beschriftungen und Datenextreme.",
 study="Crowdsourcing von „Wichtigkeit“ per BubbleView-Klicks auf Hunderten Designs und Visualisierungen; Training vollständig konvolutionaler Netze; Anwendungen wie Thumbnails und Retargeting mit Hunderten Testpersonen.",
 results=["Vorhersagen schlagen klassische Salienzmodelle für Fotos und liegen auf dem Niveau des besten Deep-Learning-Salienzmodells",
          "Automatische Thumbnails enthielten vor allem Titel, Haupttext und Datenextreme",
          "Suche in 60 Vorschaubildern: 1,96 Klicks mit Importance-Thumbnails vs. 3,25 mit verkleinerten Originalen (n = 369)"],
 do=["Titel und Kernbeschriftungen so gestalten, dass sie auch verkleinert tragen"],
 dont=["Die Kernbotschaft in Fußnoten oder Legenden verstecken"],
 limits="Modell bildet durchschnittliche Wichtigkeit ab, keine individuelle Aufgabe.",
 orig="Fig. 5 (Vorhersagen vs. Klicks), Fig. 6 (Wichtigkeit je Element), Fig. 12 (Thumbnails).",
 basis="Volltext"),

39: dict(chapter="2", fig="39-dvs-saliency",
 core="Klassische Salienzmodelle (entwickelt für Fotos) sagen nicht vorher, wohin Menschen in Charts schauen – Text ist der fehlende Faktor.",
 study="Vergleich bestehender Salienzmodelle mit Eye-Tracking-Daten auf abstrakten Datenvisualisierungen; Entwicklung des Data-Visualization-Saliency-Modells (DVS).",
 results=["Standardmodelle schneiden auf Visualisierungen schlecht ab",
          "Das DVS-Modell, das Text berücksichtigt, passt besser zu den Eye-Tracking-Daten",
          "Solche Modelle könnten als schneller Test für Designs dienen"],
 do=["Text bewusst als Aufmerksamkeitsanker platzieren"],
 dont=["Aufmerksamkeitsvorhersagen aus Foto-Tools für Dashboards übernehmen"],
 limits="Nur Abstract ausgewertet; Detailzahlen im Volltext.",
 orig="Vergleichs-Heatmaps Modell vs. Eye-Tracking im Paper.",
 basis="Abstract (Volltext-Server nicht erreichbar)"),

106: dict(chapter="2", fig="106-haroz-isotype",
 core="Piktogramme sind keine Chartjunk, solange sie selbst die Daten darstellen – rein dekorative Bilder kosten dagegen Zeit und Genauigkeit.",
 study="Fünf Crowdsourcing-Experimente zu Gedächtnis (mit und ohne zusätzliche Last), Lesegeschwindigkeit und Engagement, mit ISOTYPE-Charts, einfachen Formen und überflüssigen Hintergrundbildern.",
 results=["Überflüssiges Hintergrundbild: deutlich mehr Fehler beim Erinnern und signifikant langsameres Lesen",
          "Piktogramme als Datenmarken: keine Kosten, teils Vorteile",
          "Unter Gedächtnislast: Piktogramm-Charts mit weniger Fehlern",
          "Icons statt Balken helfen beim Erinnern kleiner Werte",
          "Achsenbeschriftungen als Text waren besser als Piktogramm-Labels",
          "Piktogramme verleiten Menschen, genauer hinzuschauen"],
 do=["Isotypen/Icon-Arrays für Mengen, die Menschen sich merken sollen", "Beschriftungen als Text"],
 dont=["Dekorative Hintergrundbilder hinter Daten"],
 limits="Einfache Charts mit drei Balken; Aufgaben simulieren Kommunikation, nicht Analyse.",
 orig="Fig. 5–7 (Gedächtnisfehler je Chartvariante), Fig. 11 (Gedächtnislast), Fig. 13 (Lesegeschwindigkeit).",
 basis="Volltext"),

# ============================================================== 3 Text
4: dict(chapter="3", fig="4-xiong-curse",
 core="Wer die Geschichte hinter den Daten kennt, hält „sein“ Muster für offensichtlich – und überschätzt systematisch, was das Publikum sieht.",
 study="Laborexperimente mit Studierenden: Sie lasen eine von mehreren Hintergrundgeschichten zu Umfragedaten, sahen dann denselben Linienchart und sagten vorher, was uninformierte Betrachter als auffälligstes Muster sehen würden.",
 results=["Die eigene Geschichte bestimmte, welches Muster als auffällig vorhergesagt wurde – trotz ausdrücklicher Anweisung, das Wissen zu ignorieren",
          "Exp. 1b ohne visuelle Hervorhebung: geprimte Muster im Mittel auf Rang 2,48 vs. 1,79 für nicht geprimte (p = .035)",
          "Je auffälliger ein Muster für einen selbst, desto auffälliger wurde es für andere eingeschätzt (rs = 0,31)",
          "Mit visueller Annotation war der Effekt noch stärker"],
 do=["Das gewünschte Muster explizit machen: Titel, Hervorhebung, Annotation", "Charts von jemandem ohne Vorwissen testen lassen: „Was siehst du?“"],
 dont=["Annehmen, dass die Daten „für sich sprechen“"],
 limits="Kleine Laborstichproben, ein Chart-Kontext (Umfragedaten).",
 orig="Fig. 3 (die drei Geschichten), Fig. 5–6 (qualitative und Rang-Ergebnisse), Fig. 9 (Exp. 1b).",
 basis="Volltext"),

31: dict(chapter="3", fig="31-kim-captions",
 core="Chart und Caption müssen dasselbe betonen – beschreibt die Caption ein unauffälliges Detail, gewinnt der Chart und die Caption wird ignoriert.",
 study="Crowdsourcing: Erst markierten Personen auffällige Stellen in 27 synthetischen und 16 echten Liniencharts; dann lasen andere Chart-Caption-Paare und schrieben ihre Takeaways auf.",
 results=["Betonen Chart und Caption dasselbe auffällige Merkmal, wird es zuverlässig zum Takeaway",
          "Beschreibt die Caption ein wenig auffälliges Merkmal, berichten Leser eher das auffälligste Chart-Merkmal",
          "Reine Achsen-Beschreibungen („Umsatz nach Monat“) ändern die Takeaways nicht",
          "Externer Kontext in der Caption erhöht die Chance, dass das beschriebene Merkmal übernommen wird (p ≈ .01–.02)"],
 do=["Das in der Caption genannte Merkmal visuell hervorheben", "Kontext liefern: warum passiert das?"],
 dont=["Botschaft nur im Text, während der Chart etwas anderes betont"],
 limits="Nur Liniencharts; Crowdsourcing-Takeaways.",
 orig="Fig. 2 (Datenformen und Prominenz), Fig. 6 (Takeaways je Caption-Typ), Fig. 8 (gute Chart-Caption-Paare).",
 basis="Volltext"),

32: dict(chapter="3", fig="32-stokes-text",
 core="Mehr Annotation wird nicht bestraft – Leser bevorzugen stark annotierte Charts gegenüber sparsamen Charts und reinem Text.",
 study="Präregistrierte Online-Studie mit 302 Personen: Rangfolgen von Liniencharts mit unterschiedlich viel Text (von keinem Text bis Absatz ohne Chart), plus freie Takeaways zu Annotationen unterschiedlicher Bedeutungsebenen.",
 results=["Die am stärksten annotierten Charts wurden in beiden Ranglisten auf Platz 1 gewählt",
          "Charts ohne Text bzw. nur mit Titel landeten zuletzt",
          "14 % bevorzugten reinen Text gegenüber dem Chart",
          "Die Bedeutungsebene der Annotation steuert das Takeaway: statistische Aussagen → statistische Takeaways, Kontext → Kontext-Takeaways",
          "Nah am Datenpunkt platzierter Text wird eher übernommen als derselbe Text im Titel"],
 do=["Annotationen direkt an die relevanten Datenpunkte setzen", "Titel für den Gesamttrend, Annotationen für Details und Kontext"],
 dont=["Aus Angst vor „Clutter“ auf erklärenden Text verzichten"],
 limits="Einfache univariate Liniencharts; Präferenz ≠ Verständnis.",
 orig="Fig. 1 (die vier Varianten), Fig. 3 (feine Varianten), Fig. 6 (Rangfolge-Ergebnisse).",
 basis="Volltext"),

40: dict(chapter="3", fig="40-xiong-arrangements",
 core="Wie Balken angeordnet sind, bestimmt, welchen Vergleich Menschen spontan ziehen – und selbst Experten sagen das oft falsch vorher.",
 study="Crowdsourcing: Personen beschrieben frei, was sie in Balkencharts sehen (vier Anordnungen: vertikal gestapelt, nebeneinander, überlagert, gestapelt); zweite Studie mit 45 Viz-Experten von Adobe und Tableau.",
 results=["Menschen vergleichen am ehesten Balken, die ausgerichtet und räumlich nah sind",
          "Vertikal/nebeneinander: fördern Vergleiche innerhalb einer Gruppe",
          "Überlagert (gruppiert): fördert globales Maximum und Vergleiche zwischen Gruppen",
          "Experten wählten für mehrere Vergleichstypen eine andere Anordnung als die, die bei Laien tatsächlich funktionierte"],
 do=["Vor dem Charten festlegen, welcher Vergleich die Botschaft ist – und diese Balken direkt nebeneinanderstellen"],
 dont=["Sich allein auf die eigene Design-Intuition verlassen"],
 limits="2×3-Balkencharts; kodierte Freitexte.",
 orig="Fig. 1 (Anordnungen), Fig. 5 (12 Vergleichstypen), Fig. 6–7 (Heatmaps), Table 2 & 9 (Empfehlungen).",
 basis="Volltext"),

# ============================================================== 4 Irreführung
105: dict(chapter="4", fig="105-pandey-deceptive",
 core="Die Klassiker der Chart-Manipulation wirken massiv: Abgeschnittene Achsen, Fläche als Menge und gestauchte Seitenverhältnisse vergrößern den wahrgenommenen Unterschied um 58–130 %.",
 study="Crowdsourcing-Studien mit Kontroll- und manipulierten Charts (ca. 250 Personen für Übertreibung, weitere für Umkehrung); gefragt wurde „Wie groß ist der Unterschied?“ bzw. „Was ist die Aussage?“.",
 results=["Linie mit gestauchtem Seitenverhältnis: 3,19 vs. 1,39 (Skala 1–5)",
          "Balken mit abgeschnittener Achse: 2,77 vs. 1,45",
          "Blasen mit Fläche als Menge: 2,71 vs. 1,71",
          "Invertierte Achse: 97,5 % falsche Antworten vs. 18,4 % in der Kontrollgruppe",
          "Individuelle Unterschiede (z. B. Chart-Vertrautheit) schützten nicht zuverlässig"],
 do=["Achsenbereich und Seitenverhältnis bewusst und begründet wählen"],
 dont=["Umgekehrte Achsen ohne sehr deutliche Kennzeichnung", "Werte über Kreisdurchmesser statt Fläche skalieren"],
 limits="Einzelne, einfache Stimuli; Likert-Antworten.",
 orig="Fig. 2–5 (die vier Tricks), Fig. 7 (Stimuli), Fig. 8 & Table 2–3 (Ergebnisse).",
 basis="Volltext"),

13: dict(chapter="4", fig="13-correll-truncation",
 core="Eine abgeschnittene y-Achse vergrößert den empfundenen Effekt – bei Balken UND Linien, und selbst Achsenbrüche oder Verläufe als Warnsignal verhindern das nicht.",
 study="Crowdsourcing-Experimente, in denen die y-Achse bei 0 %, 25 % oder 50 % des Wertebereichs begann; Designs: normale Balken, Linie, Balken mit Verlauf, Balken mit Achsenbruch; Frage nach der „Schwere“ des Unterschieds.",
 results=["Je stärker abgeschnitten, desto größer der empfundene Effekt – in allen Designs",
          "Achsenbruch-Symbol und Verlaufsfüllung änderten die empfundene Schwere nicht nennenswert",
          "Die Verzerrung bleibt, selbst wenn Leute die Zahlen korrekt ablesen",
          "Einzelwerte wurden bei Achse ab 25 % ungenauer geschätzt"],
 do=["Achsenbereich an der Größe der Effekte ausrichten, die wirklich bedeutsam sind", "Bei Linien, die Schwankungen zeigen sollen, ist ein Start ≠ 0 legitim – aber bewusst"],
 dont=["Sich auf Achsenbruch-Symbole als „Entschärfung“ verlassen"],
 limits="Kontextfreie Stimuli; die Autoren lehnen die pauschale Regel „immer bei 0 starten“ ausdrücklich ab.",
 orig="Fig. 3 (Beispiele, wo ≠ 0 sinnvoll ist), Fig. 4 (Alternativen), Fig. 6 & 8 (Ergebnisse).",
 basis="Volltext"),

61: dict(chapter="4", fig="61-lisnic-misleading",
 core="Im echten Leben lügen Menschen mit Charts selten über Designtricks – meist über korrekte Charts plus falsche Schlussfolgerungen.",
 study="Analyse von Tweets mit Visualisierungen aus der COVID-19-Debatte; kategorisiert wurden Designverstöße und Argumentationsfehler.",
 results=["Verstöße gegen Designrichtlinien waren nicht der dominante Weg der Irreführung",
          "Sie führten auch nicht überproportional zu Argumentationsfehlern",
          "Häufiger: Cherry-Picking, falsche Kausalität, fehlender Kontext bei sauber gezeichneten Charts"],
 do=["Bei eigenen Charts den Schluss prüfen, nicht nur die Achsen", "Kontext (Zeitraum, Vergleichsbasis, Unsicherheit) mitliefern"],
 dont=["Irreführung nur als Designproblem betrachten"],
 limits="Ein Thema (COVID-19), eine Plattform (Twitter).",
 orig="Die Beispielsammlung typischer Argumentationsfehler im Paper.",
 basis="Abstract (verlinktes PDF war ein falsches Dokument und wurde verworfen)"),

62: dict(chapter="4", fig="62-lo-misinformed",
 core="Aus über 1.000 real gemeldeten Fällen entsteht eine Landkarte irreführender Visualisierungen: 74 Problemtypen entlang der gesamten Analysekette.",
 study="Offene Codierung von über 1.000 als irreführend gemeldeten Visualisierungen aus dem Netz; Taxonomie mit 12 Kategorien.",
 results=["74 Problemtypen in 12 Kategorien, verteilt über die Phasen Daten-Input, Designwahl, Plotten, Wahrnehmung & Interpretation",
          "Viele Probleme sind logische Fehlschlüsse, nicht Grafikfehler",
          "Konventionen und geringe Data Literacy werden ausgenutzt",
          "Ungewöhnliche Charttypen bieten neue Täuschungsmöglichkeiten"],
 do=["Die Taxonomie als Checkliste für Reviews von Berichten/Dashboards nutzen"],
 dont=["Nur auf die „bekannten“ Tricks (y-Achse) achten"],
 limits="Nur gemeldete Fälle – unentdeckte Irreführung fehlt.",
 orig="Fig. 1 (Taxonomie der 74 Probleme), Fig. 2–5 (Beispiele je Phase).",
 basis="Volltext"),

71: dict(chapter="4", fig="71-gaba-fairness",
 core="Ob Menschen ein unfaires ML-Modell wählen, hängt vom Design ab: Als Text erklärt, wiegt Fairness schwerer als im Balkendiagramm.",
 study="Mehrere kontrollierte Crowdsourcing-Experimente mit über 1.500 Personen: Auswahl zwischen Modellen mit unterschiedlicher Rendite und Verzerrung zwischen Geschlechtern; 8 Text- und 4 Balken-Varianten.",
 results=["Fairness wurde häufiger priorisiert, wenn die Information als Text statt als Balken kam",
          "Die explizite Warnung „Modell ist verzerrt“ wirkte stärker als die Darstellung vergangener verzerrter Ergebnisse",
          "Frauen wählten häufiger das fairere Modell als Männer",
          "Für Kunden entschieden Personen fairer als für sich selbst; bei höheren Gesamtrenditen wurde Fairness wichtiger"],
 do=["Kritische Eigenschaften (Fairness, Risiko) zusätzlich klar in Worten benennen"],
 dont=["Annehmen, dass ein Balkendiagramm ethisch relevante Unterschiede „neutral“ vermittelt"],
 limits="Hypothetische Investitionsszenarien.",
 orig="Fig. 3 (Wahlverhalten), Fig. 4 (Strategien), Fig. 5 (Text- vs. Balkenvarianten), Fig. 6 (Warnhinweise).",
 basis="Volltext"),

# ============================================================== 5 Entscheidungen
63: dict(chapter="5", fig="63-xiong-causality",
 core="Balkendiagramme und Text verleiten eher zu Kausalschlüssen als Scatterplots und Linien – weil sie Daten in zwei Gruppen verdichten.",
 study="Drei Crowdsourcing-Experimente: Dieselben korrelativen Daten (z. B. Frühstück und Schulnoten) als Text, Balken, Linie oder Scatterplot; Zustimmung zu Korrelations- und Kausalaussagen plus freie Schlussfolgerungen.",
 results=["Kausale Schlüsse in freien Antworten: Text 39 %, Balken 34 %, Scatter 21 %, Linie 18 %",
          "Korrekte Korrelationsbeschreibung: Linie 76 %, Scatter 69 %, Balken 53 %, Text 50 %",
          "Die Aggregation in zwei Gruppen treibt die Kausal-Deutung stärker als die Kodierung selbst",
          "Einige hielten Balken für Ergebnisse kontrollierter Experimente"],
 do=["Korrelationsdaten als Scatterplot mit allen Punkten zeigen", "Explizit sagen: „Zusammenhang, kein Beweis für Ursache“"],
 dont=["Korrelative Daten zu zwei Balken „wenig vs. viel“ verdichten"],
 limits="Plausibilität der Kausalbeziehung wirkte ebenfalls stark; Folgestudie (Fansher 2022) fand keinen generellen „Grafik-Effekt“.",
 orig="Fig. 1 (vier Darstellungen derselben Daten), Fig. 9 (Codierung der Freitexte).",
 basis="Volltext"),

69: dict(chapter="5", fig="69-ottley-bayes",
 core="Bei Wahrscheinlichkeitsaufgaben (Bayes) bringt die Formulierung mehr als eine Grafik – und Text plus Grafik zusammen hilft nicht automatisch.",
 study="Zwei Crowdsourcing-Experimente mit einer medizinischen Testaufgabe: (1) verschiedene Textformulierungen, (2) sechs Text- und Visualisierungsdesigns, dazu ein Test der räumlichen Fähigkeit.",
 results=["Nur durch Umformulieren stieg die Trefferquote von 5,4 % auf 42,4 %",
          "Beste Designs (strukturierter/vollständiger Text oder nur Grafik): 71–77 %",
          "Storyboard 49 %, Kontroll-Text 51 %; Text + Grafik kombiniert war nicht besser als Text allein",
          "Personen mit hoher räumlicher Fähigkeit erreichten mit einigen Designs bis zu 100 %"],
 do=["Wahrscheinlichkeiten in natürlichen Häufigkeiten formulieren („10 von 1.000“)", "Entweder sehr klaren Text oder eine eigenständige Grafik (Icon Array)"],
 dont=["Text und Grafik mit denselben Zahlen doppeln und auf Synergie hoffen"],
 limits="Eine Aufgabenart (Diagnosetest); Analyse nur mit Laien ohne Statistikausbildung.",
 orig="Table 3 (die sechs Designs), Fig. 2 (Trefferquoten), Fig. 3 (nach räumlicher Fähigkeit).",
 basis="Volltext"),

73: dict(chapter="5", fig="73-kim-bayesian",
 core="Menschen interpretieren Daten im Licht ihrer Vorannahmen – ungefähr wie Bayesianer, aber bei großen Datenmengen glauben sie den Daten zu wenig.",
 study="Drei Crowdsourcing-Studien: Vorannahmen zu einem Anteil (z. B. Umfrageergebnis) abfragen, Daten zeigen, danach die aktualisierte Überzeugung erfragen; Vergleich mit der normativen Bayes-Lösung und mehreren Abfragetechniken.",
 results=["Bei kleinen Stichproben passen die Urteile im Mittel gut zu approximativer Bayes-Inferenz",
          "Bei großen Stichproben (N = 750.000) bleiben Menschen deutlich unsicherer, als sie rational sein sollten",
          "Das vorherige Abfragen der Vorannahme verringert die Abweichung, aber nicht zuverlässig",
          "Bayes-Modelle eignen sich als Bewertungsrahmen für Visualisierungen"],
 do=["Bei kontroversen Themen die Erwartung des Publikums aufgreifen („Viele denken X – die Daten zeigen Y“)", "Stichprobengröße sichtbar machen"],
 dont=["Annehmen, dass große Zahlen automatisch überzeugen"],
 limits="Einfache Anteilswerte; Online-Stichprobe.",
 orig="Fig. 1 (Bayes-Idee), Fig. 3 (Übergewichtung von Prior vs. Daten), Fig. 10 (implizierte Stichprobengröße).",
 basis="Volltext"),

74: dict(chapter="5", fig="74-li-decision",
 core="Wahrnehmungsvorteile übertragen sich nicht automatisch auf echte Entscheidungen: Balken oder Torte änderten die Wahl eines Doktorvaters kaum.",
 study="Crowdsourcing auf der Website CSrankings: Studierende bewerteten Professoren-Profile mit Publikationen als Balken- oder Tortendiagramm; Faktorenanalyse der Eindrücke.",
 results=["Zwei Faktoren: Produktivität und Interdisziplinarität",
          "Produktivität war bei beiden Charttypen der stärkere Treiber (r = 0,62 Balken, 0,47 Torte)",
          "Unterschied zwischen Balken und Torte nicht signifikant",
          "Hypothese „Balken betonen Menge, Torten Anteile → andere Entscheidungen“ nicht bestätigt"],
 do=["Charts im realen Entscheidungskontext testen, nicht nur im Labor"],
 dont=["Aus Low-Level-Wahrnehmungsstudien direkt auf Geschäftsentscheidungen schließen"],
 limits="Ein Kontext, stark männliche Stichprobe (7,9 % weiblich laut Web-Statistik).",
 orig="Fig. 1 (Stimuli), Table 2 (Korrelationen), Fig. 5 (Antworten je Bedingung).",
 basis="Volltext"),

47: dict(chapter="5", fig="47-hullman-uncertainty",
 core="Wie wird geprüft, ob Unsicherheits-Visualisierungen funktionieren? Meist falsch herum: Gemessen wird Ablesegenauigkeit statt Entscheidungsqualität.",
 study="Taxonomie mit sechs Ebenen, angewendet auf 86 Studien mit 372 Evaluationspfaden.",
 results=["Der Großteil der Studien misst Performance und Zufriedenheit",
          "Nur wenige Studien erklären, warum ein Design besser ist",
          "Einfache Alternativen (Text, gar keine Unsicherheit) werden selten mitgetestet",
          "Empfehlung: Entscheidungen mit echten Anreizen testen und Strategien der Nutzer erheben"],
 do=["Bei eigenen Tests messen, ob Menschen bessere Entscheidungen treffen – nicht nur, ob sie Werte ablesen können"],
 dont=["Unsicherheit weglassen, weil sie „zu kompliziert“ ist, ohne es getestet zu haben"],
 limits="Methodik-Survey, keine eigenen Nutzerdaten.",
 orig="Fig. 1 (Taxonomie), Fig. 2 (372 Evaluationspfade).",
 basis="Volltext"),

54: dict(chapter="5", fig="54-dimara-biases",
 core="154 kognitive Verzerrungen, geordnet nach der Aufgabe, bei der sie beim Arbeiten mit Visualisierungen auftreten.",
 study="Literatur-Survey zu kognitiven Biases, neu geordnet nach sieben Aufgabenkategorien der Datenanalyse.",
 results=["Sieben Kategorien: Schätzen, Entscheiden, Hypothesen bewerten, Kausal zuordnen, Erinnern, Meinung äußern, Sonstiges",
          "Nur ein kleiner Teil der Biases ist bisher im Visualisierungskontext empirisch untersucht",
          "Die Taxonomie hilft, bei einem Design gezielt nach passenden Biases zu fragen"],
 do=["Die Taxonomie als Checkliste bei Entscheidungs-Dashboards nutzen (z. B. Ankereffekt, Decoy-Effekt)"],
 dont=["Annehmen, dass eine korrekt gezeichnete Grafik zu unverzerrten Entscheidungen führt"],
 limits="Nur Abstract ausgewertet.",
 orig="Die große Taxonomie-Tabelle im Paper.",
 basis="Abstract (Volltext hinter Bot-Schutz)"),

# ============================================================== 6 Literacy
113: dict(chapter="6", fig="113-galesic-graph-literacy",
 core="Etwa ein Drittel der Erwachsenen in Deutschland und den USA hat eine geringe Graph Literacy und geringe Rechenfähigkeit – und nur 16–19 % beachten unterschiedliche Achsenbeschriftungen.",
 study="Entwicklung eines 13-Item-Tests zur Graph Literacy; repräsentative Stichproben in Deutschland (n = 495) und den USA (n = 492), dazu Experimente, ob Grafiken bei Risikoinformationen helfen.",
 results=["Im Schnitt 9 von 13 Aufgaben richtig (DE 9,4; US 9,3)",
          "Rund 15 % können den Wert eines beschrifteten Balkens nicht ablesen",
          "Zwei Linien mit unterschiedlichen Achsenbeschriftungen vergleichen: nur 15,5 % (DE) bzw. 19,3 % (US) richtig",
          "Grafiken helfen nur Menschen mit ausreichender Graph Literacy; wer niedrige Rechenfähigkeit UND niedrige Graph Literacy hat, profitiert nicht von Icon Arrays",
          "Graph Literacy korreliert mit Bildung (DE 0,29, US 0,54)"],
 do=["Für breite Zielgruppen einfache Grundformen wählen und Kernwerte beschriften", "Gleiche Skalen bei Vergleichscharts"],
 dont=["Unterschiedliche Achsen in nebeneinanderliegenden Charts", "Dual-Axis-Charts für Laien"],
 limits="Fokus auf Gesundheits- und Risikoinformation.",
 orig="Table 2 (Trefferquote je Aufgabe), Fig. 2–4 (Graph Literacy × Numeracy).",
 basis="Volltext"),

76: dict(chapter="6", fig="76-vlat",
 core="Der Standardtest für Visualization Literacy: 53 Fragen zu 12 Charttypen – und er zeigt, dass gestapelte Charts für Laien die größten Stolpersteine sind.",
 study="Testentwicklung nach psychometrischem Standard (Blueprint, Expertenvalidierung, Testlauf mit 191 Personen, Itemanalyse).",
 results=["Mittlerer Score 28,8 von 53 (SD 8,2)",
          "Reliabilität ω = 0,76; Korrelation mit dem Lernen eines unbekannten Charts r = 0,64",
          "Sehr leicht: Extremwerte in Linien (97 %), Anteile in Torten vergleichen (100 %)",
          "Sehr schwer: absolute Werte in gestapelten Flächen (15 %), Schiefe im Histogramm (16 %), Verhältnisse in gestapelten Balken (36 %)"],
 do=["Die Charttypen mit hohen Trefferquoten für breite Zielgruppen bevorzugen"],
 dont=["Gestapelte Flächen- und Balkencharts nutzen, wenn Laien absolute Werte ablesen sollen"],
 limits="Einfache, schulbuchartige Aufgaben; eine Online-Stichprobe.",
 orig="Fig. 2 (die 12 Test-Visualisierungen), Table 2 (Schwierigkeit jeder Frage), Fig. 3 (Korrelation).",
 basis="Volltext"),

77: dict(chapter="6", fig="77-mini-vlat",
 core="Visualization Literacy in 12 Fragen messen – fast so gut wie mit dem 53-Fragen-VLAT.",
 study="Auswahl von 12 VLAT-Items per Expertenvalidierung und Item-Total-Korrelation; Validierung mit Online-Stichprobe und einem Test zu parallelen Koordinaten.",
 results=["Reliabilität ω = 0,72, Inhaltsvalidität 0,6",
          "Starke Korrelation mit dem vollen VLAT",
          "Sagt vorher, wie gut jemand einen unbekannten Charttyp lernt",
          "Mittelwert 6,4 von 12 Punkten in der Validierungsstichprobe"],
 do=["Vor einem Workshop per Mini-VLAT das Niveau des Publikums einschätzen"],
 dont=["Visualization Literacy des Publikums voraussetzen"],
 limits="Misst nur das Lesen/Interpretieren, nicht Erstellen oder kritisches Denken.",
 orig="Fig. 1 (die 12 Visualisierungen), Table 2 (Items), Fig. 2 (Korrelation).",
 basis="Volltext"),

79: dict(chapter="6", fig="79-boerner-literacy",
 core="Selbst wissenschaftsinteressierte Museumsbesucher können viele gängige Visualisierungen weder benennen noch lesen.",
 study="Mehrphasige Studie in drei US-Science-Museen: 273 Besucher (Jugendliche und Erwachsene) sahen je 5 von 20 Visualisierungen und sollten sie benennen, erklären und einordnen.",
 results=["Viele hatten Probleme, Visualisierungen zu benennen und zu interpretieren",
          "Basis-Charts, Karten und Graphen waren vertrauter als Netzwerkdarstellungen",
          "Netzwerk-Layouts konnte fast niemand lesen",
          "Interpretationen stützten sich oft auf Oberflächenmerkmale wie Farbe"],
 do=["Für Laien bei bekannten Formen bleiben oder unbekannte Formen kurz erklären („So liest man diese Grafik“)"],
 dont=["Netzwerkgrafiken oder exotische Formen ohne Leseanleitung zeigen"],
 limits="Nur Abstract ausgewertet.",
 orig="Die Übersicht der 20 Visualisierungen und die Vertrautheitswerte im Paper.",
 basis="Abstract (Volltext bei SAGE)"),

# ============================================================== 7 Storytelling
102: dict(chapter="7", fig="102-segel-heer-genres",
 core="Der Klassiker zum Daten-Storytelling: sieben Genres und das Spektrum von autorgeführt bis lesergeführt.",
 study="Designraum-Analyse von 58 narrativen Visualisierungen aus Journalismus, Wissenschaft und Lehre.",
 results=["Sieben Genres: Magazin-Stil, annotierter Chart, geteiltes Poster, Flussdiagramm, Comic, Slideshow, Film/Animation",
          "Zentrale Spannung: autorgeführte Botschaft vs. lesergeführte Exploration",
          "Typische Mischstrukturen: Martiniglas (erst Story, dann freie Exploration), interaktive Slideshow, Drill-down-Story",
          "Werkzeuge: visuelle Struktur, Hervorhebung, Übergänge, Navigation"],
 do=["Für Präsentationen das Martiniglas nutzen: klare Botschaft zuerst, dann Raum für Fragen"],
 dont=["Ein reines Exploration-Dashboard als „Story“ verkaufen"],
 limits="Qualitative Designanalyse, keine Wirksamkeitsmessung.",
 orig="Die Genre-Übersicht und das Designraum-Diagramm im Paper.",
 basis="Volltext"),

81: dict(chapter="7", fig="81-mckenna-flow",
 core="Visualisierungen und animierte Übergänge steigern das Engagement bei Daten-Stories – ob man scrollt oder klickt, ist weniger wichtig.",
 study="Analyse von 80 Web-Datenstories (7 „Flow-Faktoren“), zwei explorative Interviewstudien und eine Crowdsourcing-Studie mit 240 Personen zum Engagement.",
 results=["Versionen mit Visualisierungen und Animationen wurden bevorzugt und als ansprechender bewertet",
          "Stepper vs. Scroller: kein eindeutiger Sieger",
          "Nur 2 von 10 Interviewten wollten eine Fortschrittsanzeige",
          "Scroll-Hijacking und ruckelnde Navigation frustrieren"],
 do=["Bei Web-Stories Übergänge animieren, damit Leser dem Wechsel folgen können"],
 dont=["Scrollverhalten kapern oder Navigation träge machen"],
 limits="Eine Story, subjektives Engagement.",
 orig="Table 1 (Flow-Faktoren der 80 Stories), Fig. 4 (Engagement-Scores), Fig. 5 (Präferenzen).",
 basis="Volltext"),

107: dict(chapter="7", fig="107-boy-storytelling",
 core="Eine vorangestellte Story macht Menschen nicht neugieriger darauf, selbst in den Daten zu stöbern.",
 study="Feldexperimente im Web mit echten Besuchern einer Visualisierungsseite; Vergleich von Varianten mit und ohne einleitende Story.",
 results=["Die einleitende „Story“ erhöhte das Explorationsverhalten nicht",
          "Storytelling und Engagement mit der eigenen Analyse sind verschiedene Ziele"],
 do=["Storytelling für eine Botschaft einsetzen, nicht als Köder für Self-Service-Exploration"],
 dont=["Erwarten, dass Story-Intros die Nutzung eines Dashboards steigern"],
 limits="Nur Abstract/TLDR ausgewertet.",
 orig="Die Engagement-Metriken der Feldexperimente im Paper.",
 basis="Abstract (Volltext hinter Bot-Schutz)"),

86: dict(chapter="7", fig="86-boy-anthropographics",
 core="Menschenfiguren statt Balken erzeugen nicht mehr Empathie – die Effekte auf Mitgefühl und Spendenbereitschaft waren nahezu gleich.",
 study="Crowdsourcing-Experimente mit Menschenrechtsdaten: eine sich füllende Menschenfigur, Gruppen einzelner Figuren und ein Standard-Chart im Vergleich.",
 results=["Anthropomorphe Grafiken und Standard-Charts wirkten sehr ähnlich auf Empathie und prosoziales Verhalten",
          "Die Folgestudie (Morais et al. 2021) fand mit großen Stichproben höchstens einen kleinen Effekt"],
 do=["Wenn Emotion das Ziel ist: auf konkrete Einzelgeschichten und Kontext setzen, nicht nur auf die Chartform"],
 dont=["Menschen-Icons als garantierten Empathie-Verstärker einsetzen"],
 limits="Nur Abstract ausgewertet.",
 orig="Die getesteten Darstellungsvarianten im Paper.",
 basis="Abstract (ACM-PDF nicht frei ladbar)"),

88: dict(chapter="7", fig="88-wang-comics",
 core="Data Comics schlagen Infografiken: mehr Freude, mehr Engagement und besseres Verständnis und Erinnern.",
 study="Zwei Studien: kontrollierte Laborstudie und eine Studie in freier Wildbahn mit Comics, Infografiken und illustrierten Texten.",
 results=["Teilnehmende bevorzugten Comics bei Freude, Fokus und Engagement",
          "Comics verbesserten Verständnis und Erinnerung an die Informationen"],
 do=["Komplexe Zusammenhänge sequenziell erzählen – Panel für Panel, wie in einer guten Folienabfolge"],
 dont=["Alle Informationen auf eine einzige Infografik pressen"],
 limits="Nur Abstract ausgewertet.",
 orig="Die Beispiel-Comics und die Engagement-Ergebnisse im Paper.",
 basis="Abstract (ACM-PDF nicht frei ladbar)"),

104: dict(chapter="7", fig="104-pandey-persuasive",
 core="Charts überzeugen stärker als Tabellen – aber nur Menschen ohne feste Meinung; wer stark dagegen ist, lässt sich eher von Tabellen überzeugen.",
 study="Crowdsourcing-Experiment mit 720 Teilnehmenden zu kontroversen Themen (z. B. Videospiele und Gewalt); Einstellung vor und nach Chart oder Tabelle.",
 results=["Bei neutraler oder schwacher Ausgangsmeinung: Charts wirkten überzeugender als Tabellen",
          "Bei stark gegenteiliger Meinung: Tabellen wirkten eher",
          "Gründe gegen Meinungsänderung: Skepsis gegenüber Daten, Verankerung in Grundüberzeugungen, Komplexität"],
 do=["Vor kritischem Publikum auch die Tabelle bzw. die Rohzahlen zeigen"],
 dont=["Bei skeptischen Stakeholdern nur auf einen polierten Chart setzen"],
 limits="Paper-PDF nicht verfügbar; Zahlen aus Abstract und Vortragsfolien zum Paper.",
 orig="Die Ergebnis-Plots nach Ausgangseinstellung im Paper.",
 basis="Abstract + Sekundärquelle (Vortragsfolien)"),

112: dict(chapter="7", fig="112-robertson-animation",
 core="Gapminder-Animationen sind schnell und machen Spaß im Vortrag, führen aber zu vielen Fehlern – für die Analyse sind Small Multiples besser.",
 study="Laborexperiment: Animation, Traces (alle Spuren in einem Bild) und Small Multiples, jeweils im Präsentations- und im Analysemodus, mit kleinem und großem Datensatz.",
 results=["Präsentation: Animation am schnellsten (15,8 s vs. 25,3 s Small Multiples, 27,8 s Traces)",
          "Analyse: Animation am langsamsten (83,1 s vs. 45,7 s Small Multiples, 55,0 s Traces)",
          "Small Multiples signifikant genauer als Animation (p < .001); Gesamt-Trefferquote nur 65 %",
          "Animation wurde als „fun“ empfunden, verwirrte aber („die Punkte flogen überall hin“)"],
 do=["Animation im Vortrag nur mit klarer, einfacher Geschichte und wenigen Punkten", "Für die eigene Analyse Small Multiples"],
 dont=["Viele Punkte animieren, die ihre Richtung wechseln"],
 limits="Alle drei Techniken skalieren nicht über ca. 200 Datenpunkte.",
 orig="Fig. 1–3 (die drei Darstellungen), Fig. 4 (Genauigkeit), Table 3 (Bewertungen).",
 basis="Volltext"),

# ============================================================== 8 Business & Überblick
93: dict(chapter="8", fig="93-bartram-tables",
 core="Für die meisten Business-Nutzer ist die Tabelle kein Vorstadium der Visualisierung, sondern ihr wichtigstes Werkzeug – wer keinen Zugriff auf die Rohdaten bietet, verliert sie an Excel.",
 study="Qualitative Interviewstudie mit „Data Workern“ – Menschen, die mit Daten arbeiten, sich aber nicht als Analysten sehen.",
 results=["Tabellen werden im gesamten Prozess genutzt: als Datenquelle, Arbeitsfläche, Prüfwerkzeug und Präsentationsartefakt",
          "„Reiche Tabellen“: unangetastete Master-Tabelle, Randnotizen, farbliche Markierungen, mehrzellige Strukturen",
          "Nutzer nehmen lieber mühsame manuelle Arbeit in Kauf, als automatischen Operationen zu vertrauen, die sie nicht nachvollziehen können",
          "Direkter Zugriff auf die Basisdaten schafft Vertrauen und Kontrolle"],
 do=["In Dashboards immer einen Drill-down zur Tabelle anbieten", "Tabellen als eigenständiges Visualisierungsformat ernst nehmen"],
 dont=["Daten nur aggregiert zeigen, ohne Weg zu den Einzelwerten"],
 limits="Qualitativ, eher kleine Stichprobe.",
 orig="Fig. 1 (Beispiel einer „reichen Tabelle“), Table 1 (Teilnehmende).",
 basis="Volltext"),

80: dict(chapter="8", fig="80-franconeri-what-works",
 core="Die beste Einzelübersicht des Feldes: Wie das visuelle System Daten verarbeitet und welche Designregeln sich daraus ableiten – ideale Grundlage für den Vortrag.",
 study="Umfassendes Review aus der Psychologie (Psychological Science in the Public Interest) zu Wahrnehmung, Kognition, Bildung und Unsicherheitskommunikation.",
 results=["Das visuelle System erfasst globale Statistiken (Mittelwert, Trend, Ausreißer) schnell und parallel",
          "Einzelne Werte zu vergleichen ist dagegen langsam und seriell – ein Vergleich nach dem anderen",
          "Gruppierung (Nähe, Farbe, Anordnung) steuert, welche Vergleiche Menschen ziehen",
          "Illusionen und Verzerrungen: Achsenmanipulation, Seitenverhältnis, Flächen-Kodierung, Farbkarten",
          "Unsicherheit besser als Verteilung zeigen (Dichte, Dotplots, HOPs) als als Fehlerbalken; der Hurrikan-Kegel wird oft als Sturmgröße missverstanden",
          "Nur 1 % der Mittelstufenschüler konnte ein Weg-Zeit-Diagramm korrekt zeichnen – Graph-Kompetenz muss gelernt werden"],
 do=["Die gewünschten Vergleiche durch Nähe und Farbe vorgeben", "Arbeitsgedächtnis entlasten: direkte Labels statt Legenden", "Konventionen respektieren (oben = mehr, rechts = später)"],
 dont=["Das Publikum viele Einzelvergleiche selbst ziehen lassen"],
 limits="Review; Tiefe je Thema begrenzt, aber mit Verweisen auf alle Primärstudien.",
 orig="Fig. 2 (Stärken und Grenzen der visuellen Verarbeitung), Fig. 4 (Illusionen), Fig. 7–9 (Vergleiche und Gruppierung), Fig. 22 (Unsicherheit).",
 basis="Volltext"),
}
